apiVersion: v1
kind: ConfigMap
metadata:
  name: powergrid-config
  namespace: powergrid
data:
  config.yml: |
    server:
      host: "0.0.0.0"
      port: 4080
      environment: "production"
    
    websocket:
      max_connections: 1000
      read_timeout: 30s
      write_timeout: 10s
      ping_interval: 25s
      max_message_size: 8192
    
    game:
      max_players_per_game: 6
      min_players_per_game: 2
      game_timeout: 45m
      turn_timeout: 5m
      lobby_timeout: 10m
      max_concurrent_games: 100
    
    database:
      type: "postgres"
      connection_string: "postgres://powergrid:powergrid@postgres:5432/powergrid?sslmode=disable"
      max_connections: 25
      max_idle_connections: 5
    
    logging:
      level: "info"
      format: "json"
      file: "/dev/stdout"
    
    security:
      cors_origins:
        - "*"
      rate_limit:
        requests_per_minute: 60
        burst: 10
      max_rooms: 1000
    
    monitoring:
      enabled: true
      metrics_endpoint: "/metrics"
      health_endpoint: "/health"
    
    performance:
      enable_compression: true
      cache_static_files: true
      max_cpu_cores: 4
    
    mobile:
      connection_retry_attempts: 3
      connection_retry_delay: 5s
      background_ping_interval: 30s
      low_data_mode: false
    
    features:
      chat: true
      spectator_mode: true
      game_recording: true
      statistics: true
      leaderboards: true
      tournaments: false