// Generates migrations/0002_seed.sql from go_server/maps/*.json plus the default deck
// and achievement list. Run with: node scripts/build-seed.ts  (Node 24 strips types natively)
import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { DEFAULT_ACHIEVEMENTS, DEFAULT_DECK } from "../src/domain/deck-default.ts"

const here = dirname(fileURLToPath(import.meta.url))
const mapsDir = resolve(here, "../../maps")
const out = resolve(here, "../migrations/0002_seed.sql")

const q = (s: string) => `'${s.replace(/'/g, "''")}'`

const lines: Array<string> = [
  "-- Generated by scripts/build-seed.ts. Do not edit by hand; re-run `pnpm seed:build`.",
  ""
]

lines.push("INSERT OR REPLACE INTO power_plant_decks (id, name, description, is_default) VALUES")
lines.push("  ('standard', 'Standard deck', 'Plant set carried over from the Go server', TRUE);")
lines.push("INSERT OR REPLACE INTO power_plants (deck_id, number, capacity, resource_type, resource_cost) VALUES")
lines.push(
  DEFAULT_DECK.map((d) => `  ('standard', ${d.number}, ${d.capacity}, ${q(d.resourceType)}, ${d.resourceCost})`).join(",\n") + ";"
)
lines.push("")

lines.push("INSERT OR IGNORE INTO achievements (achievement_id, name, description, category, icon, points, criteria) VALUES")
lines.push(
  DEFAULT_ACHIEVEMENTS.map(
    (a) => `  (${q(a.id)}, ${q(a.name)}, ${q(a.description)}, ${q(a.category)}, ${q(a.icon)}, ${a.points}, ${q(a.criteria)})`
  ).join(",\n") + ";"
)
lines.push("")

for (const file of readdirSync(mapsDir).filter((f) => f.endsWith(".json")).sort()) {
  const raw = readFileSync(join(mapsDir, file), "utf8")
  const map = JSON.parse(raw) as {
    id: string
    name: string
    description?: string
    playerCount: { min: number; max: number }
  }
  const compact = JSON.stringify(JSON.parse(raw))
  lines.push(
    `INSERT OR REPLACE INTO maps (id, name, description, player_min, player_max, data, is_active, version) VALUES (` +
      `${q(map.id)}, ${q(map.name)}, ${q(map.description ?? "")}, ${map.playerCount.min}, ${map.playerCount.max}, ${q(compact)}, TRUE, 1);`
  )
}

writeFileSync(out, lines.join("\n") + "\n")
console.log(`wrote ${out}`)
